### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by ghost** [datastax/cla-enforcer#2]
I get error when trying to heroku run rake cla:enforce[username/repository]

TypeError: no implicit conversion of nil into String
/app/lib/cla/github_client.rb:86:in `join'
/app/lib/cla/github_client.rb:86:in`subscribe'
/app/Rakefile:20:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in`call'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in`each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:172:in`invoke_with_call_chain'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:150:in`invoke_task'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in`each'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:115:in`run_with_threads'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:78:in`block in run'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in`run'

**Comment by avalanche123** [comment]
looks like you haven't set the `HOSTNAME` env variable, this should be whatever your heroku hostname is, e.g. `https://myappname.herokuapp.com/`

**Comment by ghost** [comment]
@avalanche123 I am certain I have and just double checked everything is setup properly from the credentials to the hostname.

**Comment by avalanche123** [comment]
if you look at https://github.com/datastax/cla-enforcer/blob/master/lib/cla/github_client.rb#L86, there are only a few variables that could lead to this error, `@hostname` (which we know is set), `@github_hostname` (which is optional and defaults to github.com), `repo` and `uri` which come from the rake command params. I suggest you add some debugging statement to see the values of those variables to help diagnose this issue
