### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by ermiyaeskandary** [datastax/cla-enforcer#3]
It doesn't send the emails :(

**Comment by avalanche123** [comment]
We're using it on datastax/java-driver and others

**Comment by ermiyaeskandary** [comment]
So could you help me troubleshoot this ?

**Comment by ermiyaeskandary** [comment]
Would appreciate it :+1:

**Comment by ermiyaeskandary** [comment]
https://claenforcer.herokuapp.com/ in case you need it. It just doesn't show the page which is supposed to show when the email has been sent...

**Comment by ermiyaeskandary** [comment]
Ah - I get https://claenforcer.herokuapp.com/unauthenticated @avalanche123 when I press "Sign in with Github"

**Comment by ermiyaeskandary** [comment]
Alternative used : https://github.com/sylvainc/ak-oca-clabot

**Comment by ermiyaeskandary** [comment]
Alternative - search cla assistant on GitHub . Works great !
